services:
  server:
    build:
      context: .
    volumes:
       - db_data_sqlite:/var/lib/kutt
       - custom:/kutt/custom
    environment:
      DB_FILENAME: "/var/lib/kutt/data.sqlite"
      JWT_SECRET: "2lpvxpDOJZsdXYPOdGxtzBrCsZeMPsqb5IBZx0Np8gw"
#    ports:
#      - 3000:3000
volumes:
  db_data_sqlite:
  custom: